name: Test flutter

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.29.0
    - name: test-flutter
      run: |
        flutter --version
        cd ./flutter
        flutter pub get
        flutter test
